const courseData = [
  {
    id: 1,
    category: "Career & Industry",
    title: "Careers in Cyber",
    description:
      "Discover diverse cybersecurity careers, essential skills, and industry opportunities today.",
    topics: [
      "Overview of Cyber Careers",
      "Educational Paths",
      "Industry Certifications",
      "Job Market Trends",
    ],
    difficulty: "Beginner",
    image: require("../../assets/img/CareersInCyber/landing.jpg"),
    state: "published",
    link: "/CareersInCyber",
    favorite: false,
    myCourses: false,
  },
  {
    id: 2,
    category: "Tools & Techniques",
    title: "Burp Suite",
    description:
      "Master Burp Suite fundamentals, empowering cybersecurity testing and vulnerability assessment.",
    topics: [
      "Learn about different careers in cyber",
      "Hack your first application",
      "Defend against a live cyber attack",
      "Explore security topics in the industry",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/Burp_Suit/BurpSuit_Content.png"),
    state: "published",
    link: "/Burp_Suit",
    favorite: false,
    myCourses: false,
  },
  {
    id: 3,
    category: "Fundamentals",
    title: "Cookies",
    description:
      "Understand cookies’ roles, security implications, storage methods, and manipulation techniques.",
    topics: [
      "What Are Cookies?",
      "What are Cookies Used For?",
      "Where are Cookies Stored?",
      "Cookies Manipulation",
    ],
    difficulty: "Beginner",
    image: require("../../assets/img/cookies/Cookies_transparent.png"),
    state: "published",
    link: "/cookies",
    favorite: false,
    myCourses: false,
  },
  {
    id: 4,
    category: "Vulnerabilities",
    title: "SQL Injection",
    description:
      "Identify SQL injection flaws, extract hidden data, and secure applications.",
    topics: [
      "Retrieving hidden data",
      "SQL injection UNION attacks",
      "Finding columns with a useful data type",
      "Using a SQL injection UNION attack to retrieve interesting data",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/SQL_Injection/landing3.png"),
    state: "published",
    link: "/sql_Injection",
    favorite: false,
    myCourses: false,
  },
  {
    id: 5,
    category: "Vulnerabilities",
    title: "Unrestricted File Upload",
    description:
      "Explore file upload risks, techniques, and methods to safeguard applications.",
    topics: [
      "What is Unrestricted File Upload?",
      "Why is it Dangerous?",
      "Attack Techniques",
      "Exploitation Scenarios",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/Unrestricted File Upload/card_image.png"),
    state: "published",
    link: "/UnrestrictedFileUpload",
    favorite: false,
    myCourses: false,
  },
  {
    id: 6,
    category: "Fundamentals",
    title: "Linux Fundamentals",
    description:
      "Build essential Linux skills, mastering commands, filesystem navigation and operations.",
    topics: [
      "Running Your First Few Commands",
      "Interacting with the Filesystem",
      "Searching for Files",
      "Introduction to Shell Operators",
    ],
    difficulty: "Beginner",
    image: require("../../assets/img/linux/card_image.png"),
    state: "published",
    link: "/linux",
    favorite: false,
    myCourses: false,
  },
  {
    id: 7,
    category: "Vulnerabilities",
    title: "Access Control Vulnerabilities",
    description:
      "Learn to detect and mitigate access control vulnerabilities in applications.",
    topics: [
      "What are Access Control Vulnerabilities?",
      "Types of Access Control Flaws",
      "Exploitation Examples",
      "Mitigation Techniques",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/ACV/Landing.jpg"),
    state: "published",
    link: "/AC_Vuln",
    favorite: false,
    myCourses: false,
  },
  {
    id: 8,
    category: "Vulnerabilities",
    title: "Broken Authentication",
    description:
      "Secure authentication mechanisms to prevent account takeovers and data breaches.",
    topics: [
      "Weak Passwords",
      "Session Management Issues",
      "Lack of MFA",
      "Credential Stuffing",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/Broken Authentication/card_image.png"),
    state: "published",
    link: "/broken-auth",
    favorite: false,
    myCourses: false,
  },
  {
    id: 9,
    category: "Fundamentals",
    title: "Bash Scripting",
    description:
      "Develop efficient Bash scripts to automate tasks and system management.",
    topics: ["simple bash scripts", "Variables", "Parameters", "Arrays"],
    difficulty: "Beginner",
    image: require("../../assets/img/bash/bash_course_logo.png"),
    state: "published",
    link: "/bash-scripting",
    favorite: false,
    myCourses: false,
  },
  {
    id: 10,
    category: "Vulnerabilities",
    title: "Business Logic Vulnerabilities",
    description:
      "Analyze business logic flaws, exploitation methods, and strategies for mitigation.",
    topics: [
      "Understanding Business Logic",
      "Identifying Flaws",
      "Exploitation Techniques",
      "Mitigation Strategies",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/BLV/Landing.jpg"),
    state: "published",
    link: "/BL_Vuln",
    favorite: false,
    myCourses: false,
  },
  {
    id: 11,
    category: "Vulnerabilities",
    title: "Insecure Direct Object Reference(IDOR)",
    description:
      "Explore IDOR vulnerabilities, unauthorized access, common examples, and mitigation strategies.",
    topics: [
      "What is IDOR?",
      "Why is it Dangerous?",
      "Common Examples.",
      "Exploitation Techniques.",
      "Mitigation Strategies.",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/IDOR/Insecure_Direct_Object_Reference.png"),
    state: "published",
    link: "/Insecure_Direct_Object_Reference(IDOR)",
    favorite: false,
    myCourses: false,
  },
  {
    id: 12,
    category: "Tools & Techniques",
    title: "Obfuscation",
    description:
      "Learn code obfuscation techniques to protect intellectual property and security.",
    topics: [
      "What are Obfuscation & Deobfuscation?",
      "Why do we use Obfuscation?",
      "Javascript Obfuscation",
      "JS Deobfuscation Tools",
    ],
    difficulty: "Beginner",
    image: require("../../assets/img/Obfuscation/card_image.png"),
    state: "published",
    link: "/obfuscation",
    favorite: false,
    myCourses: false,
  },
  {
    id: 13,
    category: "Vulnerabilities",
    title: "Cross Site Request Forgery (CSRF)",
    description:
      "Understand CSRF attack vectors, mitigation techniques, and prevention best practices.",
    topics: [
      "Understanding CSRF",
      "Exploitation Methods",
      "Prevention Techniques",
      "Real-world Examples",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/CSRF/landing.jpg"),
    state: "published",
    link: "/CSRF",
    favorite: false,
    myCourses: false,
  },
  {
    id: 14,
    category: "Vulnerabilities",
    title: "Path Traversal",
    description:
      "Discover path traversal techniques and prevention measures for secure files.",
    topics: [
      "Path traversal techniques",
      "Directory traversal prevention",
      "Secure file access mechanisms",
      "Case Studies",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/Path__Traversal/Photo_Content_Path_Traversal.png"),
    state: "published",
    link: "/Path__Traversal",
    favorite: false,
    myCourses: false,
  },
  {
    id: 15,
    category: "Fundamentals",
    title: "Cryptography",
    description:
      "Master cryptography principles, encryption types, and techniques for secure communications.",
    topics: [
      "What is Cryptography?",
      "What is Steganography?",
      "How does Steganography differ from Cryptography?",
      "Types of Encryption",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/Cryptography/card_image.png"),
    state: "published",
    link: "/cryptography",
    favorite: false,
    myCourses: false,
  },
  {
    id: 16,
    category: "Fundamentals",
    title: "Regular expressions",
    description:
      "Craft effective regular expressions for text matching, searching, and parsing.",
    topics: [
      "Basics of Regex",
      "Character Classes",
      "Quantifiers and Grouping",
      "Practical Examples",
    ],
    difficulty: "Beginner",
    image: require("../../assets/img/Regex/Landing.jpg"),
    state: "published",
    link: "/Regex",
    favorite: false,
    myCourses: false,
  },
  {
    id: 17,
    category: "Vulnerabilities",
    title: "Cross-Site Scripting",
    description:
      "Identify and mitigate cross-site scripting risks in modern web applications.",
    topics: [
      "What is Cross-Site Scripting?",
      "Types of XSS",
      "Exploitation Techniques",
      "Mitigation Strategies",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/Cross_Site_Scripting/xss.jpeg.jpg"),
    state: "published",
    link: "/xss",
    favorite: false,
    myCourses: false,
  },
  {
    id: 18,
    category: "Tools & Techniques",
    title: "wireshark",
    description:
      "Utilize Wireshark for deep network traffic analysis and security monitoring.",
    topics: [
      "Wireshark Overview",
      "Collection Methods",
      "ARP Traffic",
      "ICMP & TCP Traffic",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/wireshark/card_image.png"),
    state: "published",
    link: "/wireshark",
    favorite: false,
    myCourses: false,
  },
  {
    id: 19,
    category: "Fundamentals",
    title: "Hashing",
    description:
      "Understand hashing concepts, algorithms, security implications, and best practices thoroughly.",
    topics: [
      "Introduction to Hashing",
      "Common Hashing Algorithms",
      "Security Implications",
      "Best Practices",
    ],
    difficulty: "Beginner",
    image: require("../../assets/img/Hashing/landing.jpg"),
    state: "published",
    link: "/Hashing",
    favorite: false,
    myCourses: false,
  },
  {
    id: 20,
    category: "Vulnerabilities",
    title: "Command Injection",
    description:
      "Learn command injection techniques, exploitation risks, and secure coding practices.",
    topics: [
      "Understanding Command Injection",
      "Networking Weaknesses",
      "Common Web Attacks",
      "Using the Linux OS",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/Command Injection/Content_Command_Injection.jpg"),
    state: "published",
    link: "/Command_Injection",
    favorite: false,
    myCourses: false,
  },
  {
    id: 21,
    category: "Vulnerabilities",
    title: "File Inclusion",
    description:
      "Examine file inclusion flaws, exploit methods, and robust remediation strategies.",
    topics: [
      "Path Traversal",
      "Local File Inclusion (LFI)",
      "Remote File Inclusion (RFI)",
      "Remediation",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/File Inclusion/card_image.png"),
    state: "published",
    link: "/fileinclusion",
    favorite: false,
    myCourses: false,
  },
  {
    id: 22,
    category: "Fundamentals",
    title: "Digital Forensics",
    description:
      "Investigate digital evidence using forensic techniques for accurate cyber investigations.",
    topics: [
      "Introduction to Digital Forensics",
      "Evidence Collection",
      "Analysis Techniques",
      "Case Studies",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/AudFor/landing.png"),
    state: "published",
    link: "/Digital_Forensics",
    favorite: false,
    myCourses: false,
  },
  {
    id: 23,
    category: "Vulnerabilities",
    title: "Insecure Deserialization",
    description:
      "Detect insecure deserialization risks, prevent code execution, and secure data.",
    topics: [
      "Serialization and Deserialization",
      "Remote Code Execution (RCE)",
      "Data Tampering Techniques",
      "Preventing Insecure Deserialization",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/Insecure_Deserialization/Content_Insecure_Photo.jpg"),
    state: "published",
    link: "/Insecure_Deserialization",
    favorite: false,
    myCourses: false,
  },
  {
    id: 24,
    category: "Vulnerabilities",
    title: "Server Side Template Injection (SSTI)",
    description:
      "Understand SSTI risks, exploit techniques, and prevention strategies for templates.",
    topics: [
      "Introduction",
      "SSTI Vulnerabilities",
      "Constructing a SSTI Attack",
      "Prevention Strategies",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/Server Side Template Injection/card_image.png"),
    state: "published",
    link: "/SSTI",
    favorite: false,
    myCourses: false,
  },
  {
    id: 25,
    category: "Tools & Techniques",
    title: "API Hacking & Testing",
    description:
      "Master API hacking techniques, testing methodologies, and security assessment procedures.",
    topics: [
      "API Fundamentals",
      "Common Vulnerabilities",
      "Testing Tools",
      "Mitigation Strategies",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/Api_Hacking/landing.png"),
    state: "published",
    link: "/Api_Hacking",

    favorite: false,
    myCourses: false,
  },
  {
    id: 26,
    category: "Fundamentals",
    title: "Race Condition",
    description:
      "A race condition occurs when multiple processes access shared resources simultaneously in an uncontrolled manner, leading to unexpected errors or security vulnerabilities.",
    topics: ["Topic 1", "Topic 2", "Topic 3", "Topic 4"],
    difficulty: "Intermediate",
    image: require("../../assets/img/Condition_Race/Race Condition.png"),
    state: "published",
    link: "/Race_Condition",
    favorite: false,
    myCourses: false,
  },
  {
    id: 27,
    category: "Vulnerabilities",
    title: "Captcha Bypass",
    description:
      "Examine captcha bypass methods, security flaws, and advanced prevention techniques.",
    topics: [
      "Introduction to Captcha",
      "Bypass Techniques",
      "Real-world Examples",
      "Prevention Strategies",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/Captcha Bypass/card_image.png"),
    state: "published",
    link: "/captchabypass",
    favorite: false,
    myCourses: false,
  },
  {
    id: 28,
    category: "Vulnerabilities",
    title: "click jacking",
    description:
      "Investigate click jacking strategies, analyze attack mechanisms, and implement countermeasures.",
    topics: [
      "What is Click Jacking?",
      "Attack Techniques",
      "Prevention Methods",
      "Case Studies",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/Click_Jacking/landing.jpg"),
    state: "published",
    link: "/Click_Jacking",
    favorite: false,
    myCourses: false,
  },
  {
    id: 29,
    category: "Fundamentals",
    title: "Server Side Request Forgery (SSRF)",
    description:
      "Placeholder course offering preliminary topics, soon updated with comprehensive content.",
    topics: ["Topic 1", "Topic 2", "Topic 3", "Topic 4"],
    difficulty: "Hard",
    image: require("../../assets/img/Server Side Template Injection/Untitled.png"),
    state: "published",
    link: "/ssrf",
    favorite: false,
    myCourses: false,
  },
  {
    id: 30,
    category: "Vulnerabilities",
    title: "JWT attacks",
    description:
      "Examine JWT attack vectors, token vulnerabilities, and secure handling methods.",
    topics: [
      "Introduction to JWT",
      "Common Attack Vectors",
      "Security Best Practices",
      "Mitigation Techniques",
    ],
    difficulty: "Intermediate",
    image: require("../../assets/img/JWT attacks/card_image.png"),
    state: "published",
    link: "/jwtattacks",
    favorite: false,
    myCourses: false,
  },
];

export default courseData;
